### ISSUE TITLE
Set default landing page per user

### ISSUE THREAD

**Issue by HLFH** [juliushaertl/apporder#10]
Hi,

I saw your fantastic AppOrder plugin (thank you!!), then I thought that if we want to push the idea further, it would be interesting to be able to set a default landing page per user as said in https://github.com/owncloud/core/issues/8160.

I don't know if you plan to do it within your plugin.

Thanks,
HLFH

**Comment by hitam4450** [comment]
I certainly support this suggestion to place this feature e.g. inside this app, until nothing has been implemented into the administration app yet!

regards, hitam4450

**Comment by juliushaertl** [comment]
Thanks for your suggestion, I will take a look if it is something that can be implemented easily.

**Comment by hitam4450** [comment]
Hi,
The general app order works fine and without any problems.

However, as mentioned and discussed on several occasions and in different sub-projects (apps) the subject
and a solution of an "individual landing page at login" on a per user basis is still pending.
For this reason I open this issue.

At login the "app order" per user should be the same as the "admin" app order. After rearranging the "per user app order" it will present the "individual landing page" for each user at login, superseding the "general admin app order" as discussed else where.

regards, hitam4450

**Comment by juliushaertl** [comment]
This could be implemented by adding a kind of landing page route to the app, which needs to be set as default landing page in Nextcloud/ownclouds config.php. Then we could set a custom landing page per user inside of this app and simply add a second redirect.

Sadly I have not that much time at the moment, so if anyone wants to start implementing this inside of the apporder app, I welcome any help. Otherwise this is on my list for later

**Comment by hitam4450** [comment]
Unfortunately I am not a PHP programmer, otherwise I would love to help and start implementing!

Sorry!

regards, hitam4450

**Comment by juliushaertl** [comment]
@hitam4450 just had some time to take a look and started implementing this feature at #16 

Would be great if you could do some testing.

**Comment by juliushaertl** [comment]
Ok, this feature is now in version 0.3.0.

**Comment by HLFH** [comment]
@juliushaertl Hi! Thank you!! You saved my life. It's fully working. I have several users and it helps me a lot!!

**Comment by hirschrobert** [comment]
Thanks for the great work. But it doesn't seem to work with nc 11.0.3. Activity stream is set to default but it lands at files. Any idea what could be the reason?

**Comment by juliushaertl** [comment]
@hirschrobert Can you open a seperate issue for that?

**Comment by hirschrobert** [comment]
sorry, my bad. didn't read the part of making your app as default in config.php. did that now and it works with nc 11.0.3. thanks!

**Comment by juliushaertl** [comment]
@hirschrobert No problem. :wink:
