### ISSUE TITLE
Translation is incorrect for PT BR

### ISSUE THREAD

**Issue by LeoColman** [juliushaertl/apporder#100]
Hi!

The translation is completely incorrect for PT-BR.
I've added suggestions and opened issues on Transifex, but I don't know if there's anything else I can do to speed this fix up.

**Comment by rakekniven** [comment]
Hello,

all changes are done at Transifex.
I will close this issue here and we need to wait for the next release.

Hello @juliushaertl Any schedule for next release?

**Comment by rakekniven** [comment]
Please close this one
