### ISSUE TITLE
apporder not supported NC 22

### ISSUE THREAD

**Issue by kimcdow** [juliushaertl/apporder#102]
![image](https://user-images.githubusercontent.com/20283750/140589893-ed96822b-bda5-4e43-a54f-723421c93923.png)
![image](https://user-images.githubusercontent.com/20283750/140589941-95cae34d-e8fe-4e41-b470-65edd66bacce.png)

Folks, 
Site says it supports NC 22 not sure why I am getting this error, app order appears to work and I am not seeing errors in the log.
not sure how to provide more info or troubleshoot further.

**Comment by nursoda** [comment]
Yes, it would be nice if the app would be bumped to NC23 :)

**Comment by rakekniven** [comment]
> Yes, it would be nice if the app would be bumped to NC23 :)

See #104
