### ISSUE TITLE
Make app compatible with NC v23

### ISSUE THREAD

**Issue by rakekniven** [juliushaertl/apporder#104]
NC v23 final says: App is not compatible.

**Comment by rakekniven** [comment]
Just gave the app a try and enabled untested app on a test NC23 and works pretty well.

**Comment by nursoda** [comment]
Also tried in on 23.0.0 and seems to work fine (no entries on /settings/admin/logging, no direct access to logs though).

**Comment by rakekniven** [comment]
@juliushaertl Any chance to make a release after holidays? Merry Christmas 🎄 to you.

**Comment by juliushaertl** [comment]
New release out with version 0.14.0
