### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/apporder#11]
I installed version 0.1.1 and tried the app. The order of apps in the direct menu will be only updated after a refresh of the page! How about an automated refresh e.g. with small time laps, to update e.g. the order of apps in direct menu??

regards, hitam4450

**Comment by juliushaertl** [comment]
Thanks for the report, i'll try to add that to the next release.

**Comment by hitam4450** [comment]
and how about setting the landing page at login at the same time of reordering the menu items???

regards, hitam4450

**Comment by juliushaertl** [comment]
I'll keep this open, but at the moment I can't find any way to tell owncloud core to reload page after enabling the app.

**Comment by hitam4450** [comment]
Ok, I think this more browser related then OC !!!???

**Comment by juliushaertl** [comment]
No, we need a possibility to run some javascript code when the app was enabled, but all code from the app will only get loaded when the page is getting reloaded manually.

**Comment by hitam4450** [comment]
Ok, thanks for your reply and input!

**Comment by juliushaertl** [comment]
Closing this for now. If a possibility to do this will come up, we can reopen.
