### ISSUE TITLE
Not working with NC25

### ISSUE THREAD

**Issue by jakobroehrl** [juliushaertl/apporder#112]
- [ ] Hiding apps has no effect
- [ ] Can't move apps: (with NC24 its working in the same browser)
![grafik](https://user-images.githubusercontent.com/24530680/190389790-a39d2b45-3280-496f-b974-8bbcb4e28e7f.png)

**Comment by juliushaertl** [comment]
Due to server changes with the menu, the approach that this app uses to reorder does no longer work and there is currently no way to achieve that.

I've added a note to the readme https://github.com/juliushaertl/apporder/commit/9e3399190f7f3ddb7af314685ab0d8cf95c0d3b0 and currently consider the app unmaintained for that reason.

**Comment by sunjam** [comment]
Okay, I hope this can be addressed in the future and available within Nextcloud in some manner.  It was an excellent app, so much love to it.  Bye bye apporder.  Cheers!

**Comment by nursoda** [comment]
From an admin perspective, AppOrder was a quite important app: To set default (first) and order, to not show certain apps in menu although installed, and all of that as admin/new user default with users being able to modify, or admin to enforce it. It's a real drawback in UX for the clouds I maintain.

Thanks Julius, for the work on that. I really hope (a) there is a technical way to achieve a similar feature set and (b) that someone volunteers to maintain it. (I don't, still struggle with my little app :) ).

**Comment by sunjam** [comment]
@nursoda Try [Custom Menu](https://apps.nextcloud.com/apps/side_menu) app, which allows your to customize which apps are displayed in the top bar.  Agreed that it is a bummer to lose the excellent AppOrder.

**Comment by nursoda** [comment]
> Try [Custom Menu](https://apps.nextcloud.com/apps/side_menu) app

[Not yet](https://gitnet.fr/deblan/side_menu/issues/136) available for NC25 though.

**Comment by juliushaertl** [comment]
Might but in the same hacky approach that the apporder app itself was built. The main problem with changing the order in the frontend is that it is tricky to get this right in the correct loading order and may always have side effects.

A proper way would be to ensure that the order can somehow already be handled on the backend side where the apps are sorted already by their predefined order https://github.com/nextcloud/server/blob/da01494a372c5b780ee76807325001afd1190b11/lib/private/NavigationManager.php#L136

One fairly straight forward attempt might be to emit an event in the server that an app like apporder can then listen to and adjust the navigation, I'm happy to hand over the app and release keys if anyone wants to start working on that, but cleaner would be to implement the sorting directly in server (https://github.com/nextcloud/server/issues/4917)

**Comment by szaimen** [comment]
All right, thanks for the input! Will post your comment in the issue in order to bring it forward.

**Comment by simmstein** [comment]
[Custom Menu](https://apps.nextcloud.com/apps/side_menu) >= v3.1 implements an app sorter to (unfortunately) replace AppOrder. 

I loved you app, thanks for all!

**Comment by nursoda** [comment]
> Custom Menu >= v3.1 implements an app sorter

Couldn't AppOrder use the same mechanism?

**Comment by simmstein** [comment]
Yes and no. Yes because I did it in Custom menu so it's possible to do it in AppOrder. But if AppOrder must be compatible with Custom Menu, it's not possible. In custom menu, I replace the nextcloud AppMenu componnt by a custom one. 

* https://gitnet.fr/deblan/side_menu/src/branch/master/src/AppMenu.vue
* https://github.com/nextcloud/server/blob/b617f3983a8152f2da018ddba6936dd8381a1f20/core/src/components/AppMenu.vue#L73

**Comment by nursoda** [comment]
Understood. Would it be possible to JUST use the reordering functionality (and probably some tweaks) in Custom Menu, so that reordering is available for original menu?

**Comment by simmstein** [comment]
Yeap!

**Comment by gnilebein** [comment]
> Yeap!

It looks to me like the order can only be set globally? It would be nice if the goes for each user individually. Or am I missing something here?

Is there a possibility to show only the original menu? For me, both menus are always displayed.

**Comment by simmstein** [comment]
Main support is on https://gitnet.fr/deblan/side_menu

**Comment by jcb-tn** [comment]
It's horrible, how much apps no longer working with NC25. I am very dissatisfied with the teamwork of NC. Hope someone with dev dissatisfied can get this app to go again :-) .

**Comment by crazybadger** [comment]
Very sad that this is no longer supported, and wholly agree this should be core functionality.  The ability to switch certain apps on/off for some users/groups is pretty fundamental, and reordering them a nice to have.

**Comment by battosai30** [comment]
My point : I prefer the standard menu, mainly because it's a one less click to do. _Custom menu_ does not allow to keep it.

So I hope this app will find a new energy to continue to exist ;)

**Comment by gnilebein** [comment]
> My point : I prefer the standard menu, mainly because it's a one less click to do. _Custom menu_ does not allow to keep it.
> 
> So I hope this app will find a new energy to continue to exist ;)

It is possible:

https://gitnet.fr/deblan/side_menu/issues/161#issuecomment-1320

**Comment by battosai30** [comment]
> > My point : I prefer the standard menu, mainly because it's a one less click to do. _Custom menu_ does not allow to keep it.
> > So I hope this app will find a new energy to continue to exist ;)
> 
> It is possible:
> 
> https://gitnet.fr/deblan/side_menu/issues/161#issuecomment-1320

Cool ! Thanks for the (not so obvious) tip ^^

**Comment by nursoda** [comment]
Yes, one can achieve similar results, but it requires manual fiddling each time you change your app setup. In my opinion, it would be much easier if any volunteer created a revamped apporder app that uses the mechanism side_menu uses. These two apps then would be mutually incompatible though. Or side_menu reduces complexity by moving the reorder stuff in a separate app that is compatible to with and without side_menu. *wishful thinking*

**Comment by simmstein** [comment]
> Or side_menu reduces complexity by moving the reorder stuff in a separate app that is compatible to with and without side_menu. wishful thinking

This is not in the roadmap!

**Comment by crazybadger** [comment]
Thanks for the heads up on Custom Menu.  It's a little more setup than App Order, and still on a user-by-user basis.  If there were some options to apply to groups it would be much more useful

**Comment by pReya** [comment]
> Due to server changes with the menu, the approach that this app uses to reorder does no longer work and there is currently no way to achieve that.
> 
> I've added a note to the readme [9e33991](https://github.com/juliushaertl/apporder/commit/9e3399190f7f3ddb7af314685ab0d8cf95c0d3b0) and currently consider the app unmaintained for that reason.

@juliushaertl Could you give some more details about why this won't work anymore? What changed?
