### ISSUE TITLE
apporder not compatible with Nextcloud 25.0.1

### ISSUE THREAD

**Issue by eguindos** [juliushaertl/apporder#115]
Hi

Prior to update to Nextcloud 25.0.1, the updater tells me that apporder is not compatible with this new version. My actual Nextcloud version is 24.0.7. 

Will it be compatible in a near future?

Thanks

**Comment by juliushaertl** [comment]
Please see https://github.com/juliushaertl/apporder/issues/112#issuecomment-1251940348 as the pinned issue or the README for details.
