### ISSUE TITLE
Please Update to Nextcloud 25

### ISSUE THREAD

**Issue by jet438** [juliushaertl/apporder#116]
I can't update my Nextcloud to the next level until you update your app. Nice app btw
Thanks

**Comment by herrselent** [comment]
would love to see an update for NC25, too

**Comment by jet438** [comment]
Pretty please...

**Comment by juliushaertl** [comment]
Please see the relevant README section:

> **Warning**
>
> Due to server changes this app will no longer be compatible with Nextcloud 25 and is considered unmaintained from now on. 
> For introducing the functionality upstream please follow https://github.com/nextcloud/server/issues/4917

**Comment by jet438** [comment]
Well shoot. I love this app.
