### ISSUE TITLE
Not working in NC26

### ISSUE THREAD

**Issue by mkrecek234** [juliushaertl/apporder#119]
I activate the app as untested in NC26 - however I can't seem to reorder the app icon at all in the admin interface. They just won't move. Also if you deactivate single apps, the check mark won't save it does not have any effect. @juliushaertl There is no error visible in NC log or in JS console.

Would be great if you could fix this and make it compatible to the latest version, as officially only NC24 is supported.
Very helpful feature to get your top menu cleaned up and have it logically sorted.

**Comment by juliushaertl** [comment]
Please see the README and https://github.com/juliushaertl/apporder/issues/112#issuecomment-1251940348
