### ISSUE TITLE
Error Message Version 0.1.2

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/apporder#14]
I just installed the new Version 0.1.2 on OC 9.0.4 which resulted in the following error message (See enclosed screenshot)
![apporder1](https://cloud.githubusercontent.com/assets/9738727/17211298/f1d80670-54c8-11e6-9ab1-918754c071fe.png)

regards, hitam4450

**Comment by juliushaertl** [comment]
Thanks for the report, this should be fixed now.

**Comment by hitam4450** [comment]
Ok  and Thanks ! Now, **NO** Update available!

regards, hitam4450

**Comment by juliushaertl** [comment]
Ah, please try again. Now it would work just fine.

**Comment by hitam4450** [comment]
Hi Julius , now :thumbsup::thumbsup::thumbsup:
Everything is OK!
