### ISSUE TITLE
Undefined index in settingscontroller.php (53)

### ISSUE THREAD

**Issue by daita** [juliushaertl/apporder#15]
Undefined index: at /home/www/pr0npaganda.net/cloud/nextcloud/apps/apporder/controller/settingscontroller.php#53 

Installed Collabora and then removed Documents left some empty entries in the Apps list. Added a fast in_array in your function to stop flooding my logs (and having empty icons in the listing in the admin page.

```
53c53,56
<             $result[$app] = $nav_tmp[$app];
---
>       {
>             if (in_array($app, $nav_tmp))
>             $result[$app] = $nav_tmp[$app];
>       }

```

**Comment by juliushaertl** [comment]
@daita thanks for the hint. Do you want to create a pull request for that?

**Comment by daita** [comment]
Well, looks like you've already done the job :)

**Comment by juliushaertl** [comment]
Oh sorry, i've forgot to reply. I was on mobile so I could not check if this was already implemented. Thanks for your report anyway. 

just for reference: this was added in 0fdc8cc1a9df86b39047ba2a4dc4e31f87ae9b90

**Comment by daita** [comment]
Well, strange stuff happened;

It looks like I had the 0.1.2 (appinfo/info.xml) in my apps folder with an old version of controller/settingscontroller.php. I do not know if it comes from the default installation from nextcloud, or any issue while updating but I had to disable the app and uninstall to fix that.
