### ISSUE TITLE
The menu appears twice - only in Admin account

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/apporder#17]
Hi,

i just downloaded and installed apporder 0.3 in NC 10.0 and installed a test user.
After login of the test user nothing was seen of the apporder menu in the left bar, however, it showed up twice in the admin account (see enclosed screenshot)!

regards, hitam 4450
![nextcloudapporder](https://cloud.githubusercontent.com/assets/9738727/18232334/f50b05ea-72cd-11e6-888e-e5d7f271e779.png)

**Comment by juliushaertl** [comment]
Thanks for the report, should now also be fixed on master. I'll release an update tomorrow.

**Comment by hitam4450** [comment]
I will check the fixed version tomorrow as well and report back!


regards, hitam4450
