### ISSUE TITLE
White Page in Admin- additional settings

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/apporder#19]
Hi, I am sorry to get back to you again.
Today I updated both of your apps directmenu 0.91 --> 0.92 and apporder 0.30 --> 0.31 in NC 10.0, only. After the update was complete, i wanted to check and went to Administration--additional settings and received a blank white page! I loged aou and login as a "normal user". In the user section I did not found any menu to change the app order. Doing so by moving icons in the menu bar, worked, but diid not change the landing page after an additional logout - login process.

As a user, I set the mail app as landing page, but after login I received the usual  files app as landing page!

reagrds, hitam4450

PS: After disabling **apporder**, everything in additional settings are visible !

**Comment by juliushaertl** [comment]
Thanks for the quick testing and reporting :+1: Should be fixed with 0.3.2.
