### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by GieltjE** [juliushaertl/apporder#20]
Invalid argument supplied for foreach() at apps/apporder/util.php#55 

Using owncloud 9.1 and AppOrder 0.3.2

**Comment by juliushaertl** [comment]
@GieltjE Thanks for your report.

Did this error happen on the first run of apporder on your owncloud instance?

**Comment by GieltjE** [comment]
Every time the admin page is refreshed

**Comment by juliushaertl** [comment]
OK, thanks. I'll check if I can fix that tomorrow.

**Comment by juliushaertl** [comment]
Fixed on master.
