### ISSUE TITLE
Define apporder as the default app in config.php

### ISSUE THREAD

**Issue by hitam4450** [juliushaertl/apporder#22]
Hi,

to avoid any comments, bad remarks, confusion, etc. about the functionality of the app, it should be most advisable, to make the  **apporder** the default app in config.php at installation, resp. enabling, **automatically!**

regards, hitam4450

**Comment by juliushaertl** [comment]
Thanks for the request. I don't want to have this as default setting, but I'll also add a note to the app store description so it should be easier to see for everyone that this is possible.
