### ISSUE TITLE
Doesn't work with Direct Menu app

### ISSUE THREAD

**Issue by olantrust** [juliushaertl/apporder#25]
The order doesn't stick when using the Direct Menu app (which shows icons along the top rather than in the drop-down corner menu - thus saving time when working).
https://apps.owncloud.com/content/show.php/Direct+Menu?content=169148

**Comment by juliushaertl** [comment]
Thanks for your report, can you please give some more information on what software you are using?
- Nextcloud/ownCloud
- apporder version
- direct_menu version
Are there any errors in the log files/browser console?

**Comment by olantrust** [comment]
nextcloud 10.0.1
apporder 0.3.3
direct_menu 0.9.2

This error in the log files:

{"reqId":"WCW7zB@EBnoAAD2u7ucAAAAc","remoteAddr":"212.159.128.227","app":"index","message":"Exception: {\"Exception\":\"UnexpectedValueException\",\"Message\":\"Only integers, floats and strings are allowed as value\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/olanown1\\\/public_html\\\/apps\\\/apporder\\\/service\\\/configservice.php(51): OC\\\\AllConfig->setUserValue('storm', 'apporder', 'order', NULL)\\n#1 \\\/home\\\/olanown1\\\/public_html\\\/apps\\\/apporder\\\/controller\\\/settingscontroller.php(99): OCA\\\\AppOrder\\\\Service\\\\ConfigService->setUserValue('order', 'storm', NULL)\\n#2 [internal function]: OCA\\\\AppOrder\\\\Controller\\\\SettingsController->savePersonal(NULL)\\n#3 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#4 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\AppOrder\\\\Controller\\\\SettingsController), 'savePersonal')\\n#5 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/AppFramework\\\/App.php(111): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\AppOrder\\\\Controller\\\\SettingsController), 'savePersonal')\\n#6 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('SettingsControl...', 'savePersonal', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/home\\\/olanown1\\\/public_html\\\/lib\\\/base.php(983): OC\\\\Route\\\\Router->match('\\\/apps\\\/apporder\\\/...')\\n#10 \\\/home\\\/olanown1\\\/public_html\\\/index.php(48): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/home\\\/olanown1\\\/public_html\\\/lib\\\/private\\\/AllConfig.php\",\"Line\":212}","level":3,"time":"2016-11-11T12:38:37+00:00","method":"GET","url":"\/index.php\/apps\/apporder\/ajax\/personal.php?order=%5B%22%2Findex.php%2Fapps%2Focsms%2F%22%2C%22%2Findex.php%2Fapps%2Fmail%2F%22%2C%22%2Findex.php%2Fapps%2Fcontacts%2F%22%2C%22%2Findex.php%2Fapps%2Fcalendar%2F%22%2C%22%2Findex.php%2Fapps%2Ftasks%2F%22%2C%22%2Findex.php%2Fapps%2Fownnote%2F%22%2C%22%2Findex.php%2Fapps%2Ffiles%2F%22%2C%22%2Findex.php%2Fapps%2Frichdocuments%2Findex%22%2C%22%2Findex.php%2Fapps%2Fgallery%2F%22%2C%22%2Findex.php%2Fapps%2Fbookmarks%2F%22%2C%22%2Findex.php%2Fapps%2Fnews%2F%22%2C%22%2Findex.php%2Fapps%2Factivity%2F%22%2C%22%2Findex.php%2Fapps%2Fannouncementcenter%2F%22%2C%22%2Findex.php%2Fapps%2Fspreedme%2F%22%2C%22%2Findex.php%2Fapps%2Fgpxpod%2F%22%2C%22%2Findex.php%2Fapps%2Faudioplayer%2F%22%2C%22%2Findex.php%2Fapps%2Fdocuments%2Findex%22%2C%22%2Findex.php%2Fapps%2Ffbsync%2Fstatus%22%2C%22%2Findex.php%2Fapps%2Fpolls%2F%22%2C%22%2Findex.php%2Fsettings%2Fapps%22%5D&requesttoken=CzguS2RbIzlkS3ITPyUwZ0subgMKEDM2a3sFYR8DMXU%3D%3Asak3K9MX627uSQy2st%2F12uDLS5V7eeBCbl4L7Jsp8g0%3D","user":"storm"}

**Comment by juliushaertl** [comment]
@olantrust Sorry for the long delay. 

I'm using the exact same version setup here and everything works fine. The error message looks like the javascript code isn't transfering the order to the save endpoint. 

Can you describe a bit more what is happening? Can you drag and drop icons, will the order stick? When does the error in the log files occur? Is apporder working in your setup when you have direct_menu disabled?

**Comment by zerojay** [comment]
I'm not the OP but I'm using App Order 0.3.3 with NextCloud 10.0.1 and I am not using direct_menu at all and I seem to have the exact same log errors as posted earlier in this thread.

I am able to drag and drop icons and the order sticks so long as I don't change what page I'm on. Then it reverts back to what it was previously. This appears to have started happening when I upgraded from v.0.3.2 to v0.3.3

**Comment by juliushaertl** [comment]
@zerojay Thanks for the infos.

@zerojay @olantrust Can anyone of you please also check the browser error console as well as the network console (just hit F12 in your browser window)

The network console should show a request to personal.php after you've dragged the icons around. Can you send me a screenshot of this request on your instance or right-click and copy as HAR?
![2016-12-04-103603_1916x968_scrot](https://cloud.githubusercontent.com/assets/3404133/20865260/bcf07da2-ba0d-11e6-8b6f-97fff37ccd3a.png)

**Comment by zerojay** [comment]
Here's the error log: https://zerojay.com/nextcloud/index.php/s/3GBAzCM4HtlpOjQ

**Comment by juliushaertl** [comment]
@zerojay Ok thanks, I'll try to investigate and fix that later today.

**Comment by juliushaertl** [comment]
@zerojay @olantrust I'm still not able to reproduce this. It looks like the Nextcloud core code https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Http/Dispatcher.php#L128-L158 is not setting the $order parameter correctly.

Could you also fill out the issue template about server configuration/versions and paste it here as well?
https://github.com/nextcloud/server/blob/master/issue_template.md

**Comment by juliushaertl** [comment]
@zerojay @olantrust Can you test if the reordering works with the changes in #26?

**Comment by zerojay** [comment]
Sorry it took so long to respond. I previously attempted it and found it didn't work, but just took a second look and saw that I put in a capital letter in somewhere I shouldn't have and when I fixed it, it worked, so yes, I can validate that #26 does fix this bug. Thank you.

**Comment by juliushaertl** [comment]
@zerojay No problem. Good to know that it works now. :wink:
