### ISSUE TITLE
Hide apps feature

### ISSUE THREAD

**Issue by muppeth** [juliushaertl/apporder#28]
This app is awesome! Adding possibility for users to sort app order is great. Would it be possible to be able to hide apps? I use quite some apps on my nextcloud instance and I know for a fact some of the apps are never used by some users.
My idea is to be able to hide the ones unused. Maybe could change the state to hidden when dragging the app onto "hide icon"?

**Comment by juliushaertl** [comment]
Thanks for your feature request. Dragging to an hide icon sounds like a good solution but what about showing them again. That would need an additional user interface somewhere in the settings. Do you have any idea for that? I don't want to add too much complexity to managing the menu icons.

Anyway I currently don't have the time for adding such a feature, but pull requests are always welcome.

A possible workaround might be to enable the apps just for some groups.

**Comment by muppeth** [comment]
@juliushaertl yeah started thinking about it the moment I wrote my initial post. The easiest solution would be to have another icon to view all at the end of the list (eye and eye-slash from fontawesome for example). I think it's the easiest though not nicest solution as you get extra icon there, but i guess it's better then nothing and does not require extra interface features.

**Comment by juliushaertl** [comment]
Ok, I guess we can finetune that one someone grabs this issue and starts developing. :wink:

**Comment by antil0pa** [comment]
I was thinking how to give users more control of the apps they see visible in the menu and I figured it could be done as a setting option in the Personal panel.
Something similar to the App Order in the Admin panel, were users can un-check apps they do not use:
![app_menu](https://cloud.githubusercontent.com/assets/9811268/25942655/a8bbc4a2-363d-11e7-8925-da59f5073e1c.png)

**Comment by juliushaertl** [comment]
@antil0pa I already considered to move the sorting functionality to the personal settings, to avoid building complex sorting logic for the new Nextcloud 12 menu. So this might be easy then.

**Comment by bakkegaard** [comment]
Hi there. 

I have a couple of apps I would like to code, and I thought a nice way to ease myself into it would be to help out on some existing ones. So I would like to give this one a go. 

Just a couple of questions:
1.  Should I follow the design @antil0pa suggested?
2.  I have looked a bit into the code, would it make sense to do it the same way apporder works, just with an array of the apps you want to hide?
3. There are some minor bugs (e.g. it says "Set a default order ..." in personal settings), should I open an issue for each or just make pull requests?

/Nick

**Comment by juliushaertl** [comment]
> I have a couple of apps I would like to code, and I thought a nice way to ease myself into it would be to help out on some existing ones. So I would like to give this one a go.

Great to hear that.

> Should I follow the design @antil0pa suggested?

I guess that is the best option for now. I also have not come up with a better solution.

> I have looked a bit into the code, would it make sense to do it the same way apporder works, just with an array of the apps you want to hide?

Yes, that is the way to go since there is no api to set app order / rendering in the Nextcloud server component.

> There are some minor bugs (e.g. it says "Set a default order for all users..." in personal settings), should I open an issue for each or just make pull requests?

A pull request should be fine. If you are unsure about something, it makes sense to open an issue first so we can have some discussion before you invest some time to implement things.

> On second thought it would also be possible to just remove the app from the order array?
That woun't work as the current implementation will look for missing apps in the array and just add them, in case you have just installed them.

**Comment by juliushaertl** [comment]
Fixed by #40
