### ISSUE TITLE
Make app compatible with the new Nextcloud menu

### ISSUE THREAD

**Issue by juliushaertl** [juliushaertl/apporder#29]

**Comment by MariusBluem** [comment]
Would it not be better to get this directly in the server? 🤔

**Comment by juliushaertl** [comment]
@MariusBluem Nothing for Nextcloud 12 because we already had feature freeze :wink:

**Comment by juliushaertl** [comment]
I still have not come up with a good idea how to do the organizing properly with the new menu. Since it is responsive and we will have 1-8 icons in the header as well as any number in a popover window we cannot just keep the current drag and drop.

**Comment by juliushaertl** [comment]
I've added basic support for Nc12 in master by putting a sorting UI to the personal settings.

@MariusBluem Mind opening an issue on the server so we might get discussion started there on how we could integrate the sorting functionality nicely?
