### ISSUE TITLE
Nextcloud 12 compatibility 

### ISSUE THREAD

**Issue by hubertkn** [juliushaertl/apporder#32]
Hi,
I like your app and I can not wait for NC12 support, so I have tried to use the last version from gitbub.
I have downloaded it to my server to folder apps. Then I have removed old version 0.33. Next I wanted to enable it but such error has occured:

![obraz](https://cloud.githubusercontent.com/assets/28611780/26524621/9b6c7126-4339-11e7-9709-7a88b85e694b.png)

Is it possible to use version 0.4 with NC12? What should I do to enable (and use) it?

Best regards!

**Comment by blu-IT** [comment]
Hello,

I also would appreciate very much "AppOrder" to be available for NC 12 very soon. 

**Thanks!**

Regards,
Ivan

**Comment by ColdSphinX** [comment]
A manual installation without the appstore works like this:

`cd whatever/path/to/your/nextcloud/folder
git clone https://github.com/juliushaertl/apporder.git apps/apporder
sudo -u www-data ./occ app:enable apporder`

**Comment by blu-IT** [comment]
Hi,

is it also possible to clone via git and upload via FTP to the server? I don't have full access to my Nextcloud installation... So I clone/download the full apporder repository...?

**Comment by blu-IT** [comment]
OK, upload via FTP worked so far and NC shows that the app is installed, but doesn't give me the chance to enable it :-/

**Comment by juliushaertl** [comment]
You should be able to download the master from here https://github.com/juliushaertl/apporder/archive/master.zip and just upload it to your Nextclouds app directory.

There is currently no release for 12 since there are still some bugs that need to be solved. I'll see if I find some time next week to do some fixes and release a new version.

**Comment by hubertkn** [comment]
I don't have access to my server via shell hence I need to wait till you will release official version for NC12. Hope it will be soon. 

Best regards

**Comment by blu-IT** [comment]
Hello,

I don't know how, but I succeeded activating "AppOrder" in NC 12 now - but it does **not** change the order in the direct menu bar. So we still have to wait for the approved release I guess...

Best regards

**Comment by juliushaertl** [comment]
Fixed with #44 

I'll release a new version to the app store once we have #40 ready.
