### ISSUE TITLE
Feature Request - Re-organize Icons

### ISSUE THREAD

**Issue by sunjam** [juliushaertl/apporder#33]
**Steps to Reproduce**
[1. Attempt to drag and drop an app icon in the direct menu / App Order menu to re-organize](http://imgur.com/a/QlS56)
2. Look under administrative settings for personalization of the menu

**Expected behaviour**
Applications icons can be re-ordered
Menu can be personalized to re-order or hide icons

**Actual behaviour**
Nothing changes. No personalization is available.

**Comment by bakkegaard** [comment]
To change your personal app order, you have to go to the personal settings, and find App Order. There you will be able to drag the icons in the order you like.

**Comment by juliushaertl** [comment]
What @bakkegaard said. I think we should update the readme and remove the animated gif showing the drag-and-drop in the menu.
