### ISSUE TITLE
Travis is failing

### ISSUE THREAD

**Issue by bakkegaard** [juliushaertl/apporder#38]
I think Travis is failing because on the server master branch, which we check against, the version is set to 13, which is incompatible with the current settings in apporder's info.xml.
We could change the info.xml to `<nextcloud min-version="12" max-version="13" />` and test against both the master and stable12 branch?

**Comment by juliushaertl** [comment]
Yep that is the only reason. Can you open a PR to change this as well? :wink: 

Thanks for the other pull requests, I'll try to have a look at them later today.

**Comment by bakkegaard** [comment]
Sure thing :)
