### ISSUE TITLE
User specific versus Admin designed

### ISSUE THREAD

**Issue by starlyth** [juliushaertl/apporder#43]
On NextCloud 12.0.0, I was successfully able to modify the standard default menu. It was globally applied, and works on initial login, but seems to reset itself within a session. Also, I had to manually update the config file with the apporder.

**Comment by juliushaertl** [comment]
@starlyth Can you retry this with current master, since there have been fixed some issues with the new app menu today.

**Comment by starlyth** [comment]
Timing is everything! Updated with current master, and the customizations stick. Thanks!
