### ISSUE TITLE
Feature Request - List Apps by Text Names OR Icons OR Text Names + Icons OR a mixture

### ISSUE THREAD

**Issue by sunjam** [juliushaertl/apporder#47]
**Steps to reproduce**

[1. Browse over the application menu as shown in this screen capture](http://imgur.com/a/3OJ9t)
2. Note how (...) apps listed both text names and icons, but those along the top bar do not.

**Expected behaviour**

Applications would fill the entire top bar of my browser before the (...)
Possible to display just application Icons OR Text Names OR Both OR some combination of both.

**Actual behaviour**

Only 7 app icons are currently displayed before (...) despite having plenty of browser real estate.
I'm often confused when I see an icon and have no idea what it pertains to until I mouse over it to see the text name pop up.
No option to customize.
No option to display application names with no associated icons.

**Comment by juliushaertl** [comment]
This has nothing todo with the apporder app. :wink: The menu style is part of the Nextcloud server. There will be some improvements to the app menu in https://github.com/nextcloud/server/pull/5244. Please report any further issues with that to the server repo.

**Comment by sunjam** [comment]
@juliushaertl Thanks.  How do I know which part of Nextcloud is the correct one when writing an issue or feature suggestion to Github?  It can be confusing and I definitely want to minimize wasted time.

**Comment by juliushaertl** [comment]
> How do I know which part of Nextcloud is the correct one when writing an issue or feature suggestion to Github?

Not easy to say in general. Check if there is an app in the nextcloud organisation that seems to fit, otherwise nextcloud/server is fine. In case it will not fit, people will tell you. :wink:
