### ISSUE TITLE
Apporder broken on nc12 with more then 7 apps

### ISSUE THREAD

**Issue by muppeth** [juliushaertl/apporder#48]
I noticed that app order is not working as it should when you have more then 7 apps enabled. With nextcloud12 the "..." (more apps) icon has been introduced. When moving the apps displayed on the main top bar, everything works as expected. But if you start moving apps that are in "More aps" section, apporder goes crazy and starts putting apps in random order (not set by admin, nor the user). The only way to fix it is to put order accordingly to what is being set by apporder atm, and only then manually more apps around, but only the main 7.

**Comment by bakkegaard** [comment]
I have some time next week where I can look into it.

_Sent from my Google Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bakkegaard** [comment]
I have some time next week where I can look into it.

**Comment by muppeth** [comment]
hmmm... just checked on another nextcloud instance and it seems it 
works correctly there. I will investigate my instance more in detail 
and try to figure out what is happening.

**Comment by muppeth** [comment]
Strange. While investigating the possible issue on the other instance (which just worked) I noticed that you can hide (\o/) unwanted apps. While my instance was also running 0.4.0 version the interface was still of the previous version. Quick check revealed I used git version of the app when I did update to nc12, since apporder was not in the store at the time of update. Now I swapped it with the version from store and viola, works like a charm. So typical PEBKAC on my side, sorry.

And kudos on the hide app feature!
