### ISSUE TITLE
Force app order for users

### ISSUE THREAD

**Issue by dan-nkl** [juliushaertl/apporder#50]
I want to force the app order I set in the admin settings. Is this possible yet?

**Comment by juliushaertl** [comment]
Currently it is only possible to set a default order. But i guess a setting to disable the user-dependent sorting would make sense here.

**Comment by poVoq** [comment]
Nice would be also if you could disable that users can unhide certain apps unless they are part of a certain group.

This is sort of a work around for Nextcloud not allowing public functionality for apps that are limited to groups. But if the link was permanently disabled unless you are a member of a certain group that would be almost as good.

But I understand if this is outside the scope of this app.

**Comment by szaimen** [comment]
Any update on this?

**Comment by juliushaertl** [comment]
Implemented with https://github.com/juliushaertl/apporder/pull/70 I'll prepare a new release soon.

**Comment by szaimen** [comment]
@juliushaertl any update on a new release? :)

**Comment by szaimen** [comment]
@juliushaertl any update to this?

**Comment by szaimen** [comment]
@juliushaertl what happened to the release?

**Comment by juliushaertl** [comment]
Oops, sorry about the delay. Adding this to my todo list since I need to do an app release for 19 anyways.

**Comment by szaimen** [comment]
Thank you very much for the new release!
This feature works great!

**Comment by juliushaertl** [comment]
All praise goes to @omsmet for implementing that :rocket:

**Comment by szaimen** [comment]
Thank you @omsmet for implementing this amazing feature!
