### ISSUE TITLE
Default landing page ignored

### ISSUE THREAD

**Issue by olantrust** [juliushaertl/apporder#54]
Using Nextcloud 12.

Expected:
The first item in the list set under apporder settings, is the default landing page for that user.

Actual:
Nextcloud does not respect the default landing page set by apporder (i.e. the first in the list), and reverts to going to the Files app when a user logs in.

**Comment by juliushaertl** [comment]
Have you set the default app config as required in the README?  https://github.com/juliushaertl/apporder#use-first-app-as-default-app

**Comment by juliushaertl** [comment]
Cannot reproduce that, so I'm closing this, since it seems to be a missing configuration issue. Feel free to reopen if it still occurs.
