### ISSUE TITLE
Request: add translations for transiflex

### ISSUE THREAD

**Issue by mjanssens** [juliushaertl/apporder#56]
Hi, could you adjust your app so that transifex translations are possible?
In personal settings "App Order" the words dont follow the language of the rest of the page.

**Comment by juliushaertl** [comment]
Yes, translations would be nice.

@MorrisJobke Is it possible to enable this app on the Nextcloud transifex, even if it is not in the Nextcloud org?

**Comment by MorrisJobke** [comment]
@juliushaertl Sure - @nextcloud-bot only needs push access (and admin rights, if the master branch is protected).

**Comment by MorrisJobke** [comment]
Config is in #57

**Comment by juliushaertl** [comment]
@MorrisJobke Great, thanks. Merged #57 and added @nextcloud-bot as a contributor.

**Comment by MorrisJobke** [comment]
it's now on transifex and ready to be translated: https://www.transifex.com/nextcloud/nextcloud/apporder/
