### ISSUE TITLE
Modifying the default number of apps / Changing default app.

### ISSUE THREAD

**Issue by jsavalle** [juliushaertl/apporder#59]
Hi,

Small feature requests:

**1/ Modifying the default number of apps**
Could it be possible to change the default maximum number of app display in the top - and not just the order?

For now, default behavior is to fold apps into a dropdown after it's reached 9 apps in the top.
It'd be great if we could modify the number of the app as well.

For now this can be done only my modifying the core :
_in  ../nextcloud/core/js/js.js_
`var minAppsDesktop = 8;`

Altering this number would change the current behavior on desktop (which is mainly where I think it would be useful). 

Changing the core would not be a smart idea - and it make sense to me this would be a part of the apporder application - which is already heping customizing how app are behaving. 

**2/ Changing default app**
While I know this can be changed in the config file,  it seems to me it would make sense if it would be a part of the app as well.

**Comment by juliushaertl** [comment]
> 1/ Modifying the default number of apps

I would not add a configuration entry for that. Showing all icons or as much as possible is more in the scope of the direct_menu app. See the issue there:
https://github.com/juliushaertl/direct_menu/issues/71

> 2/ Changing default app
That is already possible. Please see the README for details on how to use the first app as default app:
https://github.com/juliushaertl/apporder#use-first-app-as-default-app
