### ISSUE TITLE
Allow icons to be nested in a "more apps" icon

### ISSUE THREAD

**Issue by otyu** [juliushaertl/apporder#60]
When the width of the browser window reaches a small app icons are nested in a _**more apps**_ icon (see screenshot). It would be a nice feature if AppOrder could customize this behavior too, not depending on the window width. Further, when the width gets small, the remaining apps could be gradually absorbed in the _**more apps**_ icon.

![screenshot](https://user-images.githubusercontent.com/12646940/34782870-4bf9a928-f66d-11e7-8f08-2f429f24b23e.png)

Some suggestions for the AppOrder menu:
1) the apps unchecked are nested (instead of invisible); or
2) there could be a separator which could be moved around like the other apps, and items beneath this separator would be nested.

**Comment by juliushaertl** [comment]
I like the idea, unfortunately I don't see a proper way how we could implement this, with the code we currently use in the Nextcloud menu for this.
