### ISSUE TITLE
Enable a Pico CMS page as default page

### ISSUE THREAD

**Issue by diplodata** [juliushaertl/apporder#65]
Nice little app - should be integrated into Nextcloud core codebase IMO.

It would be nice to see the option to explicitly specify an app as the default page on login - rather than assuming the first on the list.  It would be **extra extra cool** to for Pico CMS app users to be able to specify a Pico page as the default, instead of an app.  This would enable Nextcloud admins to create a customised welcome page that users hit when they login.  As a simple html redirect it should be super easy to implement.

**Comment by juliushaertl** [comment]
You could give the external sites app a try. Although I have not tested, you could create a external site for your pico cms page and move that to the first position in apporder. Then it should use that as default page.
