### ISSUE TITLE
Make Nextcloud 14 compatible

### ISSUE THREAD

**Issue by weeman1337** [juliushaertl/apporder#67]
The app doesn't work with Nextcloud 14, yet.

Original report: https://github.com/nextcloud/server/issues/11382

**Comment by juliushaertl** [comment]
Version 0.5.0 was already released a while ago with compatibility for 14. https://apps.nextcloud.com/apps/apporder/releases?platform=14#14

I also cannot reproduce the missing settings from nextcloud/server#11382, works fine on my 14 setup. Can you reproduce the original issue @weeman1337 ?

**Comment by weeman1337** [comment]
@juliushaertl then it's my fault :(
I looked in this repos code and found a version < 14 in the app info..

I also tested in my Nextcloud 14 production instance. It's working there.

**Comment by juliushaertl** [comment]
Ah, seems i forgot to push after bumping the version. Just checked again, the 0.5.0 release supports 14 and master is now also up to date.
