### ISSUE TITLE
Nextcloud 16 compatibility

### ISSUE THREAD

**Issue by j-ed** [juliushaertl/apporder#72]
By default the app is not available for Nextcloud 16, although it seems to work without any problem by using the new function "Activate untested app".

**Comment by Grotax** [comment]
There already is a new version, which supports nc16 but it was not added to the appstore
https://github.com/juliushaertl/apporder/releases/tag/v0.7.0

**Comment by juliushaertl** [comment]
I just released 0.7.1 which is now also on the appstore.
