### ISSUE TITLE
Maintain changelog in semantic version to have a good rss feed

### ISSUE THREAD

**Issue by rakekniven** [juliushaertl/apporder#74]
Hello,

I am a happy user of your useful app.
To be up to date I am using Nextcloud news app.
Just found that your app does not provide a changelog in rss feed.
Could you change your changelog like other apps are doing it e.g. https://github.com/nextcloud/files_antivirus/blob/v2.2.0/CHANGELOG.md or contacts app (which recently had a release).

To make it more clear, your app in my news reader:

![2019-10-04_11h57_31](https://user-images.githubusercontent.com/2069590/66199152-4cd8ab00-e69e-11e9-9981-a267d295bab4.png)

Antivirus app:

![2019-10-04_11h57_45](https://user-images.githubusercontent.com/2069590/66199170-595d0380-e69e-11e9-9e3c-a0e1ea9a5961.png)

**Comment by rakekniven** [comment]
If you like I can support you

**Comment by juliushaertl** [comment]
Yes, makes sense. I must admit I just forgot to add one since the last releases always were just version bumps for new Nextcloud versions. Maybe you can create a pull request for a basic changelog file and I'll make sure to update it once I release a new version.
