### ISSUE TITLE
Suggestion: "Reset to defauts" button

### ISSUE THREAD

**Issue by tomastd** [juliushaertl/apporder#85]
I find interesting for users to have the possibility to reset their custom configuration.

Also for site administrators it could be interesting to reset to Nextcloud defaults the order of the apps.

Thank you.

**Comment by SimJoSt** [comment]
I opened a similar issue in https://github.com/juliushaertl/apporder/issues/63

**Comment by juliushaertl** [comment]
Let's track this in #63 then.
