### ISSUE TITLE
20.0.0beta3 App Order can no longer change the default app away from Dashboard

### ISSUE THREAD

**Issue by sunjam** [juliushaertl/apporder#92]
AppOrder in 20.0.0beta3 no longer allows the user to decide which app they see upon login.  Normally it would be the first app (Files on in my instance).  Now, the Dashboard will open regardless.

**Comment by juliushaertl** [comment]
What value have you set in config.php for `defaultapp`?

**Comment by sunjam** [comment]
> What value have you set in config.php for `defaultapp`?

Actually, that value is not listed in my config.php, but perhaps this is related:

```
 'app_install_overwrite' => 
  array (
    0 => 'globalsiteselector',
    1 => 'nextcloudpi',
    2 => 'contacts',
    3 => 'previewgenerator',
    4 => 'analytics',
    5 => 'workflow_script',
    6 => 'files_automatedtagging',
    7 => 'dashboardcharts',
    8 => 'breezedark',
  ),

```

**Comment by juliushaertl** [comment]
https://github.com/juliushaertl/apporder#use-first-app-as-default-app should help

**Comment by sunjam** [comment]
> https://github.com/juliushaertl/apporder#use-first-app-as-default-app should help

That is exactly what I've done within the app.
![image](https://user-images.githubusercontent.com/1787238/92407108-90c60280-f0ee-11ea-8b5a-8d360f059ac9.png)
Organized **Files** to be number one, but Dashboard is still what is shown by default.  Guess I need to add that config.php value as well.
![image](https://user-images.githubusercontent.com/1787238/92407074-768c2480-f0ee-11ea-9546-8c95a5349fa8.png)

**Comment by juliushaertl** [comment]
Yes as mentioned in the readme you need to specify the default app to be either `files` for hardcoding the first app or `apporder` to pick up the first one in the apporder sorting to your config.php :+1: 
```
'defaultapp' => 'apporder',
```
