### ISSUE TITLE
default apporder in config crashes NC site

### ISSUE THREAD

**Issue by menace133780** [juliushaertl/apporder#94]
Hello
I´m using NC 20.0.2 with AppOrder 0.11.0;
I configured the app, to only show "Files" for every user;
When I add the "'defaultapp' => 'apporder', " to the config.php, the NC site is not working any more;

Website showes:
"Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the webserver log."

Apache error.log showes:
[Thu Nov 26 08:25:34.014450 2020] [php7:error] [pid 42596] [client XXX.XXX.XXX.XXX:50140] PHP Parse error:  syntax error, unexpected ''dbtype'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/config/config.php on line 12

**Comment by juliushaertl** [comment]
[Thu Nov 26 08:25:34.014450 2020] [php7:error] [pid 42596] [client XXX.XXX.XXX.XXX:50140] PHP Parse error: syntax error, unexpected ''dbtype'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/config/config.php on line 12

Seems like a syntax error in your config.php. Please head over to the forum at help.nextcloud.com for support with this.
