### ISSUE TITLE
Not working in NC 22.1.1

### ISSUE THREAD

**Issue by mkrecek234** [juliushaertl/apporder#99]
- Deactivating icons or changing orders will not result in any change in the top menu bar

**Comment by rakekniven** [comment]
Works for me with NC 22.1.1 and app order v0.13.0

**Comment by mkrecek234** [comment]
Running same versions - for a non-admin, social login user it does not work - tried to deactivate photos, but no effect

**Comment by rakekniven** [comment]
Just tried it with non-admin and it works as well.

Are you using ldap?

Cannot test social login.

**Comment by mkrecek234** [comment]
Am using OAuth authentication from a Mailcow provider.
But seems to work now - I could not make it work in a iOS Safari browser though
